version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

sphinx:
  configuration: docs/conf.py

python:
  install:
    # install itself with pip install .
    - method: pip
      path: .
      extra_requirements:
        - docs
